spring:
  profiles:
    active: postgres
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pulseops}
    username: ${DB_USERNAME:pulseops}
    password: ${DB_PASSWORD:pulseops}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
